version: "3.8"
services:
  app:
    build: .
    container_name: urlshort-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: urlshort-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
