version: '3.8'

services:
  redis:
    image: redis:7
    container_name: urlshort-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
